# Used to speed up the split over time by reusing git's objects
cache_dir: "./.gitsplit"

# List of splits.
splits:
  - prefix: manala.hugo
    target: git@github.com:manala/ansible-role-hugo.git
  - prefix: manala.php
    target: git@github.com:manala/ansible-role-php.git

# List of references to split (defined as regexp)
origins:
  - ^master$
