# Used to speed up the split over time by reusing git's objects
cache_dir: "./.gitsplit"

# List of splits.
splits:
  - prefix: manala.accounts
    target: git@github.com:manala/ansible-role-accounts.git
  - prefix: manala.alternatives
    target: git@github.com:manala/ansible-role-alternatives.git
  - prefix: manala.ansible
    target: git@github.com:manala/ansible-role-ansible.git
  - prefix: manala.ansible-galaxy
    target: git@github.com:manala/ansible-role-ansible-galaxy.git
  - prefix: manala.apparmor
    target: git@github.com:manala/ansible-role-apparmor.git
  - prefix: manala.apt
    target: git@github.com:manala/ansible-role-apt.git
  - prefix: manala.aptly
    target: git@github.com:manala/ansible-role-aptly.git
  - prefix: manala.backup-manager
    target: git@github.com:manala/ansible-role-backup-manager.git
  - prefix: manala.beanstalkd
    target: git@github.com:manala/ansible-role-beanstalkd.git
  - prefix: manala.cloud-init
    target: git@github.com:manala/ansible-role-cloud-init.git
  - prefix: manala.deploy
    target: git@github.com:manala/ansible-role-deploy.git
  - prefix: manala.dnsmasq
    target: git@github.com:manala/ansible-role-dnsmasq.git
  - prefix: manala.docker
    target: git@github.com:manala/ansible-role-docker.git
  - prefix: manala.fail2ban
    target: git@github.com:manala/ansible-role-fail2ban.git
  - prefix: manala.files
    target: git@github.com:manala/ansible-role-files.git
  - prefix: manala.gitlab
    target: git@github.com:manala/ansible-role-gitlab.git
  - prefix: manala.heka
    target: git@github.com:manala/ansible-role-heka.git
  - prefix: manala.hugo
    target: git@github.com:manala/ansible-role-hugo.git
  - prefix: manala.influxdb
    target: git@github.com:manala/ansible-role-influxdb.git
  - prefix: manala.java
    target: git@github.com:manala/ansible-role-java.git
  - prefix: manala.keepalived
    target: git@github.com:manala/ansible-role-keepalived.git
  - prefix: manala.locales
    target: git@github.com:manala/ansible-role-locales.git
  - prefix: manala.logentries
    target: git@github.com:manala/ansible-role-logentries.git
  - prefix: manala.logrotate
    target: git@github.com:manala/ansible-role-logrotate.git
  - prefix: manala.mailhog
    target: git@github.com:manala/ansible-role-mailhog.git
  - prefix: manala.make
    target: git@github.com:manala/ansible-role-make.git
  - prefix: manala.maxscale
    target: git@github.com:manala/ansible-role-maxscale.git
  - prefix: manala.mongo-express
    target: git@github.com:manala/ansible-role-mongo-express.git
  - prefix: manala.mongodb
    target: git@github.com:manala/ansible-role-mongodb.git
  - prefix: manala.motd
    target: git@github.com:manala/ansible-role-motd.git
  - prefix: manala.mysql
    target: git@github.com:manala/ansible-role-mysql.git
  - prefix: manala.nginx
    target: git@github.com:manala/ansible-role-nginx.git
  - prefix: manala.ngrok
    target: git@github.com:manala/ansible-role-ngrok.git
  - prefix: manala.nodejs
    target: git@github.com:manala/ansible-role-nodejs.git
  - prefix: manala.npm
    target: git@github.com:manala/ansible-role-npm.git
  - prefix: manala.ntp
    target: git@github.com:manala/ansible-role-ntp.git
  - prefix: manala.oauth2-proxy
    target: git@github.com:manala/ansible-role-oauth2-proxy.git
  - prefix: manala.opcache-dashboard
    target: git@github.com:manala/ansible-role-opcache-dashboard.git
  - prefix: manala.phantomjs
    target: git@github.com:manala/ansible-role-phantomjs.git
  - prefix: manala.php
    target: git@github.com:manala/ansible-role-php.git
  - prefix: manala.phpmyadmin
    target: git@github.com:manala/ansible-role-phpmyadmin.git
  - prefix: manala.phppgadmin
    target: git@github.com:manala/ansible-role-phppgadmin.git
  - prefix: manala.phpredisadmin
    target: git@github.com:manala/ansible-role-phpredisadmin.git
  - prefix: manala.redis
    target: git@github.com:manala/ansible-role-redis.git
  - prefix: manala.rsyslog
    target: git@github.com:manala/ansible-role-rsyslog.git
  - prefix: manala.rtail
    target: git@github.com:manala/ansible-role-rtail.git
  - prefix: manala.shorewall
    target: git@github.com:manala/ansible-role-shorewall.git
  - prefix: manala.skeleton
    target: git@github.com:manala/ansible-role-skeleton.git
  - prefix: manala.sqlite
    target: git@github.com:manala/ansible-role-sqlite.git
  - prefix: manala.supervisor
    target: git@github.com:manala/ansible-role-supervisor.git
  - prefix: manala.telegraf
    target: git@github.com:manala/ansible-role-telegraf.git
  - prefix: manala.vault
    target: git@github.com:manala/ansible-role-vault.git
  - prefix: manala.vim
    target: git@github.com:manala/ansible-role-vim.git
  - prefix: manala.yarn
    target: git@github.com:manala/ansible-role-yarn.git
  - prefix: manala.zsh
    target: git@github.com:manala/ansible-role-zsh.git

# List of references to split (defined as regexp)
origins:
  - ^master$
