# Used to speed up the split over time by reusing git's objects
cache_dir: "./.gitsplit"

# List of splits.
splits:
  - prefix: manala.accounts
    target: git@github.com:manala/ansible-role-accounts.git
  - prefix: manala.alternatives
    target: git@github.com:manala/ansible-role-alternatives.git
  - prefix: manala.ansible
    target: git@github.com:manala/ansible-role-ansible.git
  - prefix: manala.apt
    target: git@github.com:manala/ansible-role-apt.git
  - prefix: manala.apparmor
    target: git@github.com:manala/ansible-role-apparmor.git
  - prefix: manala.backup-manager
    target: git@github.com:manala/ansible-role-backup-manager.git
  - prefix: manala.beanstalkd
    target: git@github.com:manala/ansible-role-beanstalkd.git
  - prefix: manala.cloud-init
    target: git@github.com:manala/ansible-role-cloud-init.git
  - prefix: manala.deploy
    target: git@github.com:manala/ansible-role-deploy.git
  - prefix: manala.files
    target: git@github.com:manala/ansible-role-files.git
  - prefix: manala.gitlab
    target: git@github.com:manala/ansible-role-gitlab.git
  - prefix: manala.hugo
    target: git@github.com:manala/ansible-role-hugo.git
  - prefix: manala.influxdb
    target: git@github.com:manala/ansible-role-influxdb.git
  - prefix: manala.java
    target: git@github.com:manala/ansible-role-java.git
  - prefix: manala.logrotate
    target: git@github.com:manala/ansible-role-logrotate.git
  - prefix: manala.make
    target: git@github.com:manala/ansible-role-make.git
  - prefix: manala.mysql
    target: git@github.com:manala/ansible-role-mysql.git
  - prefix: manala.nginx
    target: git@github.com:manala/ansible-role-nginx.git
  - prefix: manala.ngrok
    target: git@github.com:manala/ansible-role-ngrok.git
  - prefix: manala.nodejs
    target: git@github.com:manala/ansible-role-nodejs.git
  - prefix: manala.opcache-dashboard
    target: git@github.com:manala/ansible-role-opcache-dashboard.git
  - prefix: manala.php
    target: git@github.com:manala/ansible-role-php.git
  - prefix: manala.phpmyadmin
    target: git@github.com:manala/ansible-role-phpmyadmin.git
  - prefix: manala.phppgadmin
    target: git@github.com:manala/ansible-role-phppgadmin.git
  - prefix: manala.phpredisadmin
    target: git@github.com:manala/ansible-role-phpredisadmin.git
  - prefix: manala.shorewall
    target: git@github.com:manala/ansible-role-shorewall.git
  - prefix: manala.skeleton
    target: git@github.com:manala/ansible-role-skeleton.git
  - prefix: manala.sqlite
    target: git@github.com:manala/ansible-role-sqlite.git
  - prefix: manala.telegraf
    target: git@github.com:manala/ansible-role-telegraf.git
  - prefix: manala.vim
    target: git@github.com:manala/ansible-role-vim.git
  - prefix: manala.yarn
    target: git@github.com:manala/ansible-role-yarn.git
  - prefix: manala.zsh
    target: git@github.com:manala/ansible-role-zsh.git

# List of references to split (defined as regexp)
origins:
  - ^master$
