sudo: required

services:
  - docker

before_install:
  - docker pull manala/ansible-debian:wheezy
  - docker pull manala/ansible-debian:jessie

script:
  - make lint@wheezy
  - make test@wheezy
  - make lint@jessie
  - make test@jessie
