---

- name: config > Templates
  template:
    src:  "{{ item.template }}"
    dest: "{{ elao_shorewall_configs_dir }}/{{ item.file }}"
  with_items: elao_shorewall_configs
  notify:
    - shorewall restart

- name: config > Main configuration file
  lineinfile:
    dest:   "{{ elao_shorewall_main_config_file }}"
    regexp: "^{{ item.keys()[0] }}="
    line:   "{{ item.keys()[0] }}={{ item.values()[0] }}"
  with_items: "{{ elao_shorewall_main_config_options }}"
