---

- name: config > Git configuration
  template:
  when: elao_git_config is defined and elao_git_config | length
    src:    "{{ elao_git_config_template if (elao_git_config_template is not none) else 'gitconfig.j2' }}"
    dest:   "{{ elao_git_config_filepath if (elao_git_config_filepath is not none) else '/etc/gitconfig' }}"
