---

- name: config > Templates
  template:
    src:  "{{ item.template }}"
    dest: "{{ elao_shorewall_configs_dir }}/{{ item.file }}"
  with_items: elao_shorewall_configs
  notify:
    - shorewall restart
