---

- name: config > Template
  template:
    src:  "{{ elao_keepalived_config_template|ternary(elao_keepalived_config_template, 'config/empty.conf.j2') }}"
    dest: "{{ elao_keepalived_config_file }}"
  when: (elao_keepalived_config_template is not none) or (elao_keepalived_config|length)
  notify:
    - keepalived reload
