---

- name: Hosts file configuration
  lineinfile:
    dest:   /etc/hosts
    regexp: "{{ item.name|replace('.','\\.') }}"
    line:   "{{ item.ip }} {{ item.name }}"
  with_items: elao_network_config.hosts
  when: elao_network_config.hosts|length > 0

- name: Resolv file configuration
  template:
    src:  resolv.conf.j2
    dest: /etc/resolv.conf
  when: (elao_network_config.resolv.searches|length > 0) or (elao_network_config.resolv.nameservers|length > 0)
