---

- name: install > Ensure base directory exists
  file:
    path:  "{{ elao_supervisor_config_file | dirname }}"
    state: directory
    owner: root
    mode:  0755

- name: config > Config
  template:
    src:   "{{ elao_supervisor_config_template }}"
    dest:  "{{ elao_supervisor_config_file }}"
    owner: root
    mode:  0644
  notify:
    - supervisor restart
