---

- name: config > Creating zones directory.
  file:
    path:  "{{ elao_bind_dir.logs }}"
    state: directory
    owner: bind
    group: bind

- name: config > Creating log directory.
  file:
    path:  "{{ elao_bind_dir.zones }}"
    state: directory
    owner: bind
    group: bind

- name: config > Writing files.
  template:
    src:  "{{ item.src }}"
    dest: /etc/bind/{{ item.dest }}
    owner: root
    group: bind
    mode:  0644
  with_items:
    - { src: "{{ elao_bind_config_templates.named_conf_local }}",     dest: "named.conf.local" }
    - { src: "{{ elao_bind_config_templates.named_conf }}",           dest: "named.conf" }
    - { src: "{{ elao_bind_config_templates.named_conf_options }}",   dest: "named.conf.options" }
  when: item.src is defined and item.src | length
  notify:
    - bind restart

- name: config > Writing zones files
  template:
    src:   "{{ elao_bind_zones_templates ~ '/db.' ~ item.domain ~ '.j2' if (elao_bind_zones_templates is defined and elao_bind_zones_templates is not none) else 'db.' ~ item.domain ~ '.j2' }}"
    dest:  /etc/bind/zones/db.{{ item.domain }}
    owner: root
    group: bind
    mode:  0644
  with_items: elao_bind_zones
  notify:
    - bind restart

- name: config > Writing zone reverse file.
  template:
    src:   "{{ elao_bind_zones_templates ~ '/rev.' ~ item.domain ~ '.j2' if (elao_bind_zones_templates is defined and elao_bind_zones_templates is not none) else 'rev.' ~ item.domain ~ '.j2' }}"
    dest:  /etc/bind/zones/rev.{{ item.network|regex_replace('^([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})/([0-9]{1,2})$', '\\3.\\2.\\1') ~ '.in-addr.arpa' }}
    owner: root
    group: bind
    mode:  0644
  with_items: elao_bind_zones
  notify:
    - bind restart
