---
- name: configs > Templates
  template:
    src:  "{{ item.template|default(elao_sensu_configs_template) }}"
    dest: "{{ elao_sensu_configs_dir }}/{{ item.file }}"
  with_items: elao_sensu_configs
  notify:
    - sensu restart
