---

- name: config > Template
  template:
    src:   "{{ elao_mongodb_config_template|ternary(elao_mongodb_config_template, 'config/base.conf.j2') }}"
    dest:  "{{ elao_mongodb_config_file }}"
  when: (elao_mongodb_config_template is not none) or (elao_mongodb_config|length)
  notify:
    - mongodb restart
