---

- name: config > Config file
  template:
    src:  "{{ elao_composer_config_template }}"
    dest: "{{ elao_composer_home }}/config.json"

- name: config > Auth file
  template:
    src:  "{{ elao_composer_config_auth_template }}"
    dest: "{{ elao_composer_home }}/auth.json"
  when: elao_composer_config_auth|default({})|length

