---

- name: config
  template:
    src:   config.inc.php.j2
    dest:  "{{ elao_phpmyadmin_path }}/config.inc.php"
    owner: "{{ elao_phpmyadmin_user|ternary(elao_phpmyadmin_user,omit) }}"
    group: "{{ elao_phpmyadmin_user_group|ternary(elao_phpmyadmin_user_group,omit) }}"
