---

- name: config > PostgreSQL host-based authentication (hba) configuration
  template:
    src: "{{ elao_postgresql_config_hba_template }}"
    dest: /etc/postgresql/{{ elao_postgresql_version }}/main/pg_hba.conf
  when: elao_postgresql_config_hba_template is not none
  notify:
    - postgresql restart
