---

- name: config > Config file
  template:
    src:  config.json.j2
    dest: "{{ elao_composer_home_path }}/config.json"
    mode: 0644

- name: config > Auth file
  template:
    src:  auth.json.j2
    dest: "{{ elao_composer_home_path }}/auth.json"
    mode: 0644

