---

- name: config > Template
  template:
    src:   "{{ elao_redis_config_template|ternary(elao_redis_config_template, 'config/base.conf.j2') }}"
    dest:  "{{ elao_redis_config_file }}"
  when: (elao_redis_config_template is not none) or (elao_redis_config|length)
  notify:
    - redis-server restart

