---

- name: config > Template
  template:
    src:  "{{ elao_haproxy_config_template }}"
    dest: "{{ elao_haproxy_config_file }}"
  notify:
    - haproxy restart
  when: elao_haproxy_config_template is not none
