---

- name: databases > Create Influx databases
  command: "{{ elao_influxdb_influx_bin }} -execute 'CREATE DATABASE \"{{ item }}\"'"
  with_items: elao_influxdb_databases
  register: command_result
  failed_when: "command_result.rc != 0 and 'database already exists' not in command_result.stdout"
  changed_when: "command_result.rc == 0"
