---

- name: files > Force non empty dirs to symlinks
  command: "find {{ item.path|dirname }} -name {{ item.path|basename }} -type d -exec rm -r {} \\;"
  failed_when: false
  changed_when: false
  when: item.state == 'link'
  with_items: "{{ elao_files|selectattr('force', 'sameas', true)|list }}"

- name: files > File
  file:
    path:     "{{ item.path }}"
    follow:   "{{ item.follow|default(omit) }}"
    force:    "{{ item.force|default(omit) }}"
    group:    "{{ item.group|default(omit) }}"
    mode:     "{{ item.mode|default(omit) }}"
    owner:    "{{ item.owner|default(omit) }}"
    recurse:  "{{ item.recurse|default(omit) }}"
    setlevel: "{{ item.setlevel|default(omit) }}"
    setrole:  "{{ item.setrole|default(omit) }}"
    setype:   "{{ item.setype|default(omit) }}"
    seuser:   "{{ item.seuser|default(omit) }}"
    src:      "{{ item.src|default(omit) }}"
    state:    "{{ item.state|default('file') }}"
  with_items: "{{ elao_files|selectattr('content', 'undefined')|selectattr('template', 'undefined')|list }}"

- name: files > Content
  copy:
    dest:    "{{ item.path }}"
    content: "{{ item.content }}"
    force:   "{{ item.force|default(omit) }}"
    group:   "{{ item.group|default(omit) }}"
    mode:    "{{ item.mode|default(omit) }}"
    owner:   "{{ item.owner|default(omit) }}"
  with_items: "{{ elao_files|selectattr('content', 'defined')|list }}"

- name: files > Template
  template:
    src:     "{{ item.template }}"
    dest:    "{{ item.path }}"
    force:   "{{ item.force|default(omit) }}"
    group:   "{{ item.group|default(omit) }}"
    mode:    "{{ item.mode|default(omit) }}"
    owner:   "{{ item.owner|default(omit) }}"
  with_items: "{{ elao_files|selectattr('template', 'defined')|list }}"

- name: files > Acls
  acl:
    name:  "{{ item.0.path }}"
    entry: "{{ item.1 }}"
    state: present
  with_subelements:
    - "{{ elao_files|selectattr('acls', 'defined')|list }}"
    - acls
