---

- name: files > Force non empty dirs to symlinks
  command: "find {{ item.path|dirname }} -name {{ item.path|basename }} -type d -exec rm -r {} \\;"
  failed_when: false
  changed_when: false
  when: item.state in ['link']
  with_items: "{{
    manala_files
      |selectattr('force', 'sameas', true)
      |list
  }}"

- name: files > Link directory
  file:
    path:  "{{ item.path }}"
    owner: "{{ item.user|default(manala_files_user|ternary(manala_files_user,omit)) }}"
    group: "{{ item.group|default(manala_files_group|ternary(manala_files_group,omit)) }}"
    state: directory
  with_items: "{{
    manala_files
      |selectattr('state', 'sameas', 'link_directory')
      |list
  }}"

- name: files > File
  file:
    path:     "{{ item.path }}"
    follow:   "{{ item.follow|default(omit) }}"
    force:    "{{ item.force|default(omit) }}"
    owner:    "{{
      (item.state == 'link_directory')|ternary(
        omit,
        item.user|default(manala_files_user|ternary(manala_files_user,omit))
      )
    }}"
    group:    "{{
      (item.state == 'link_directory')|ternary(
        omit,
        item.group|default(manala_files_group|ternary(manala_files_group,omit))
      )
    }}"
    mode:     "{{ item.mode|default(omit) }}"
    recurse:  "{{ item.recurse|default(omit) }}"
    setlevel: "{{ item.setlevel|default(omit) }}"
    setrole:  "{{ item.setrole|default(omit) }}"
    setype:   "{{ item.setype|default(omit) }}"
    seuser:   "{{ item.seuser|default(omit) }}"
    src:      "{{ item.src|default(omit) }}"
    state:    "{{
      (item.state is defined)|ternary(
        (item.state == 'link_directory')|ternary(
          'link',
          item.state
        ),
        'file'
      )
    }}"
  with_items: "{{
    manala_files
      |selectattr('content', 'undefined')
      |selectattr('template', 'undefined')
      |selectattr('dest', 'undefined')
      |selectattr('url', 'undefined')
      |list
  }}"

- name: files > Url
  get_url:
    url:            "{{ item.url }}"
    dest:           "{{ item.path }}"
    force:          "{{ item.force|default(false) }}"
    owner:          "{{ item.user|default(manala_files_user|ternary(manala_files_user,omit)) }}"
    group:          "{{ item.group|default(manala_files_group|ternary(manala_files_group,omit)) }}"
    mode:           "{{ item.mode|default(omit) }}"
    validate_certs: "{{ item.validate_certs|default(true)|bool }}"
  with_items: "{{
    manala_files
      |selectattr('url', 'defined')
      |selectattr('path', 'defined')
      |list
  }}"

- name: files > Content
  copy:
    dest:    "{{ item.path }}"
    content: "{{ item.content }}"
    force:   "{{ item.force|default(omit) }}"
    owner:   "{{ item.user|default(manala_files_user|ternary(manala_files_user,omit)) }}"
    group:   "{{ item.group|default(manala_files_group|ternary(manala_files_group,omit)) }}"
    mode:    "{{ item.mode|default(omit) }}"
  with_items: "{{
    manala_files
      |selectattr('content', 'defined')
      |list
  }}"

- name: files > Copy
  copy:
    src:   "{{ item.src }}"
    dest:  "{{ item.dest }}"
    force: "{{ item.force|default(omit) }}"
    owner: "{{ item.user|default(manala_files_user|ternary(manala_files_user,omit)) }}"
    group: "{{ item.group|default(manala_files_group|ternary(manala_files_group,omit)) }}"
    mode:  "{{ item.mode|default(omit) }}"
  with_items: "{{
    manala_files
      |selectattr('dest', 'defined')
      |list
  }}"

- name: files > Template
  template:
    src:   "{{ item.template }}"
    dest:  "{{ item.path }}"
    force: "{{ item.force|default(omit) }}"
    owner: "{{ item.user|default(manala_files_user|ternary(manala_files_user,omit)) }}"
    group: "{{ item.group|default(manala_files_group|ternary(manala_files_group,omit)) }}"
    mode:  "{{ item.mode|default(omit) }}"
  with_items: "{{
    manala_files
      |selectattr('template', 'defined')
      |list
  }}"

- name: files > Acls
  acl:
    name:  "{{ item.0.path }}"
    entry: "{{ item.1 }}"
    state: present
  with_subelements:
    - "{{
      manala_files
        |selectattr('acls', 'defined')
        |list
    }}"
    - acls
