---

- name: plugins > Stats playbook handlers directory
  stat:
    path: "{{ playbook_dir ~ '/files/sensu/handlers/' }}"
  register: _elao_sensu_playbook_handlers

- name: plugins > Copy roles handlers files
  copy:
    src: "{{ item }}"
    dest: /etc/sensu/handlers/
    mode: 0755
  with_items:
    - sensu/handlers/
    - "{{ elao_sensu_handlers_dir }}"
  notify:
    - sensu restart

- name: plugins > Copy playbook handlers files
  copy:
    src: "{{ item }}"
    dest: /etc/sensu/handlers/
    mode: 0755
  with_items:
    - "{{ playbook_dir ~ '/files/sensu/handlers/' }}"
  when: _elao_sensu_playbook_handlers.stat.exists
  notify:
    - sensu restart
