---

- name: hosts > File
  lineinfile:
    dest:   "{{ elao_network_hosts_file }}"
    regexp: "{{ item.keys()[0]|replace('.','\\.') }}"
    line:   "{{ item.keys()[0] }} {{ item.values()[0] }}"
  with_items: elao_network_hosts
