---

- name: install > Packages
  apt:
    name:  "{{ item }}"
    state: present
    install_recommends: false
  with_items:
    - mongodb-org
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-tools
