---

- name: install > Download package
  get_url:
    url:  https://github.com/mozilla-services/heka/releases/download/v{{ elao_heka_version }}/heka_{{ elao_heka_version }}_amd64.deb
    dest: /opt/heka_{{ elao_heka_version }}_amd64.deb

- name: install > Install package
  apt:
    deb: /opt/heka_{{ elao_heka_version }}_amd64.deb

- name: install > Create heka directories
  file:
    dest:  "{{ item.path }}"
    state: directory
  with_items:
    - path:  /etc/heka/conf.d
    - path:  /var/cache/hekad

- name: install > Copy init.d script
  template:
    src:   install/init.j2
    dest:  /etc/init.d/heka
