---

- name: install > Packages
  apt:
    name:  "{{ item }}"
    state: present
  with_items:
    - postgresql-{{ manala_postgresql_version }}
    - postgresql-contrib-{{ manala_postgresql_version }}
