---

- name: install > download package
  get_url:
    url: https://s3.amazonaws.com/influxdb/influxdb_{{ elao_influxdb_version }}_amd64.deb
    dest: /opt/influxdb_{{ elao_influxdb_version }}_amd64.deb

- name: install > install package
  apt:
    deb: /opt/influxdb_{{ elao_influxdb_version }}_amd64.deb

