---

- name: install > download package
  get_url:
    url: http://get.influxdb.org/influxdb_{{ elao_influxdb_version }}_amd64.deb
    dest: /opt/influxdb_{{ elao_influxdb_version }}_amd64.deb

- name: install > install package
  apt:
    deb: /opt/influxdb_{{ elao_influxdb_version }}_amd64.deb

