---

- name: install > Packages dependencies
  apt:
    name:  libfontconfig1
    state: present

- name: install > Packages
  npm:
    name:    "{{ item }}"
    version: ~1
    state:   present
    global:  true
  with_items:
    - phantomjs


