---

- name: install > Download and install composer
  shell: "curl -sS https://getcomposer.org/installer | php -- --install-dir={{ elao_composer_bin_path }} --filename=composer"
  args:
    creates: "{{ elao_composer_bin_path }}/composer"

- name: install > Home directory
  file:
    path:  "{{ elao_composer_home_path }}"
    state: directory

- name: install > Environment variables
  lineinfile:
    dest:  /etc/environment
    line:  "COMPOSER_HOME={{ elao_composer_home_path }}"
    state: present

- name: install > Sudoers
  template:
    src:  sudoer.j2
    dest: /etc/sudoers.d/composer
  notify:
    - sudo restart
