---

  # Ensure ssh known hosts file is present
- name: known hosts file
  copy:
    dest:    /etc/ssh/ssh_known_hosts
    content: ""
    force:   no
  when: elao_ssh_known_hosts|length > 0

- name: known hosts check
  shell: "ssh-keygen -f /etc/ssh/ssh_known_hosts -F {{ item }}"
  with_items: elao_ssh_known_hosts
  register: elao_ssh_known_hosts_check
  when: elao_ssh_known_hosts|length > 0
  always_run: yes
  changed_when: false

- name: known hosts set
  shell: "ssh-keyscan -H -T 10 {{ item.item }} >> /etc/ssh/ssh_known_hosts"
  with_items: elao_ssh_known_hosts_check.results
  when: (elao_ssh_known_hosts|length > 0) and (item.stdout == "")
