---

- name: log > Logrotate
  template:
    src:  log/logrotate.j2
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode:  0644

- name: log > Files
  file:
    path:  "{{ item }}"
    owner: "{{ elao_nginx_user }}"
    group: adm
    mode:  0640
  with_items:
    - /var/log/nginx/access.log
    - /var/log/nginx/error.log
