---

# Requirements
- include: requirements.yml
  tags:
    - manala_npm

# Vars
- include: vars.yml
  tags:
    - manala_npm

# Update
- include: update.yml
  when: "{{ manala_npm['update']|default(false) }}"
  tags:
    - manala_npm
    - manala_npm.update
    - manala.update

# Packages
- include: packages.yml
  vars:
    __manala_npm_packages: "{{ (__manala_npm_packages_results.results|last).ansible_facts.__item.values() if (__manala_npm_packages_results.results|length) else [] }}"
  tags:
    - manala_npm
