---

- include: setup.yml
- include: strategy.yml
- include: shared.yml
- include: copied.yml
- include: removed.yml
- include: writables.yml
- include: tasks.yml
  with_items: "{{ manala_deploy_tasks }}"
- include: current.yml
