---

# Dependencies
- include: dependencies.yml
  tags:
    - manala_apt

# Sources list
- include: sources_list.yml
  tags:
    - manala_apt

# Repositories
- include: repositories.yml
  tags:
    - manala_apt

# Preferences
- include: preferences.yml
  tags:
    - manala_apt

# Upgrade
- include: upgrade.yml
  when: manala_apt_upgrade
  tags:
    - manala_apt
    - manala_apt.update
    - manala.update

# Packages
- include: packages.yml
  tags:
    - manala_apt
