---

# Alternatives
- include: alternatives.yml
  tags:
    - manala_ansible_galaxy

# Roles
- include: roles.yml
  tags:
    - manala_ansible_galaxy
    - manala_ansible_galaxy.update
    - manala.update
