---

- include: dependencies.yml
- include: sources_list.yml
- include: repositories.yml
- include: preferences.yml
- include: update.yml
  when: manala_apt_update or manala_apt_upgrade
- include: upgrade.yml
  when: manala_apt_upgrade
- include: packages.yml
