---

- name: packages > Manage packages
  apt:
    name:  "{{ (item) if (item is string) else (item.package) }}"
    force: "{{ item.force|default(omit) }}"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ manala_apt_packages }}"
