---

- name: packages > Manage
  npm:
    name:     "{{ item.package }}"
    global:   true
    state:    "{{ item.state|default(omit) }}"
    version:  "{{ item.version|default(omit) }}"
    registry: "{{ item.registry|default(omit) }}"
  with_items: "{{ __manala_npm_packages }}"
