---

- name: parameters > Configure kernel parameters.
  sysctl:
    name:   "{{ item.name }}"
    value:  "{{ item.value|default(omit) }}"
    state:  "{{ item.state|default(omit) }}"
    reload: "{{ item.reload|default(omit) }}"
  with_items: "{{ manala_kernel_parameters }}"
