---

# Get repositories patterns from preferences
# Following "bar@foo" syntax, get the right part, in this case, "foo"
- name: repositories > From preferences
  set_fact:
    __item: "{{ (item.split('@')[1]).split(':')[0] }}"
  with_items: "{{ elao_apt_preferences|select('string')|list }}"
  register: __elao_apt_preferences_repositories

# Expand string based repositories into arrays
# foo -> {pattern: 'foo'}
- name: repositories > Expand patterns
  set_fact:
    __item: "{{ ({'pattern': item}) if (item is string) else (item) }}"
  with_items: "{{ (elao_apt_repositories + ((__elao_apt_preferences_repositories.results|map(attribute='ansible_facts.__item')|list) if (__elao_apt_preferences_repositories.results is defined) else ([])))|unique }}"
  register: __elao_apt_repositories

# Deprecation
- name: repositories > Deprecation - Pattern 'backports'
  fail:
    msg: "Repository pattern 'backports' is deprecated, please specify 'debian_backports' or 'ubuntu_backports'"
  when: "{{ not __elao_apt_repositories|skipped and 'backports' in __elao_apt_repositories.results|map(attribute='ansible_facts.__item.pattern')|reject('undefined') }}"

# Deprecation
- name: repositories > Deprecation - Pattern 'mongodb'
  fail:
    msg: "Repository pattern 'mongodb' is deprecated, please specify version like 'mongodb_3_0'"
  when: "{{ not __elao_apt_repositories|skipped and 'mongodb' in __elao_apt_repositories.results|map(attribute='ansible_facts.__item.pattern')|reject('undefined') }}"

# Replace pattern based repositories by their values
# {pattern: 'foo'} -> {src: 'deb http://foo.com/debian }
- name: repositories > Apply patterns
  set_fact:
    __item: "{{ ({'source': elao_apt_repositories_patterns[item.pattern].source, 'key': elao_apt_repositories_patterns[item.pattern].key|default(none)}) if (item.pattern is defined) else (item) }}"
  with_items: "{{ (__elao_apt_repositories.results|map(attribute='ansible_facts.__item')|list) if (not __elao_apt_repositories|skipped) else ([]) }}"
  register: __elao_apt_repositories

- name: repositories > Key
  apt_key:
    url:   "{{ item.key.url }}"
    id:    "{{ item.key.id }}"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ (__elao_apt_repositories.results|map(attribute='ansible_facts.__item')|list) if (not __elao_apt_repositories|skipped) else ([]) }}"
  when: item.key is defined and (item.key is not none)

- name: repositories > Source
  apt_repository:
    repo:         "{{ item.source }}"
    state:        "{{ item.state|default('present') }}"
    update_cache: yes
  with_items: "{{ (__elao_apt_repositories.results|map(attribute='ansible_facts.__item')|list) if (not __elao_apt_repositories|skipped) else ([]) }}"

- name: repositories > Exclusive - find files
  command: "find -type f -name '*.list' -printf '%P\n'"
  args:
    chdir: "{{ elao_apt_repositories_dir }}"
  changed_when: false
  register: __elao_apt_repositories_find_output
  when: elao_apt_repositories_exclusive

# Here come the tricky part
# Simulate what file name ansible apt_repository module will give
# Something like "deb http://nginx.org/packages/debian/ wheezy nginx" -> "nginx_org_packages_debian.list"
- name: repositories > Exclusive - remove files
  file:
    path:  "{{ elao_apt_repositories_dir }}/{{ item }}"
    state: absent
  when: "{{ elao_apt_repositories_exclusive and (item not in __elao_apt_repositories.results|map(attribute='ansible_facts.__item.source')|map('regex_replace', '^deb https?:\\/\\/([^ ]+)[ ].*$', '\\1')|map('replace', '.', ' ')|map('replace', '/', ' ')|map('trim')|map('replace', ' ', '_')|map('regex_replace', '(.*)', '\\1.list')|list) }}"
  with_items: "{{ (__elao_apt_repositories_find_output.stdout_lines) if (not __elao_apt_repositories_find_output|skipped) else ([]) }}"
