---

- name: repositories > Handle repositories keys
  apt_key:
    url:   "{{ item.key.url }}"
    id:    "{{ item.key.id }}"
    state: "{{ item.state|default('present') }}"
  with_items: elao_apt_repositories
  when: item.key is defined

- name: repositories > Handle repositories sources
  apt_repository:
    repo:         "{{ item.source }}"
    state:        "{{ item.state|default('present') }}"
    update_cache: yes
  with_items: elao_apt_repositories
