---

- name: repositories > From preferences pass 1
  set_fact:
    _elao_apt_preferences_repositories_item: "{{ (item.split('@')[1]).split(':')[0] }}"
  with_items: elao_apt_preferences
  when: item is string
  register: _elao_apt_preferences_repositories_pass

- name: repositories > From preferences pass 2
  set_fact:
    _elao_apt_preferences_repositories: "{{ _elao_apt_preferences_repositories_pass.results|rejectattr('skipped', 'defined')|map(attribute='ansible_facts._elao_apt_preferences_repositories_item')|list|unique }}"
  when: _elao_apt_preferences_repositories_pass.results is defined

- name: repositories > Deprecation - Pattern 'backports'
  fail:
    msg: "Repository pattern 'backports' is deprecated, please specify 'debian_backports' or 'ubuntu_backports'"
  when: "{{ 'backports' in (elao_apt_repositories|select('mapping')|rejectattr('pattern', 'undefined')|map(attribute='pattern')|list + (_elao_apt_preferences_repositories|default([]) + elao_apt_repositories|select('string')|list)|unique) }}"

- name: repositories > Deprecation - Pattern 'mongodb'
  fail:
    msg: "Repository pattern 'mongodb' is deprecated, please specify version like 'mongodb_3_0'"
  when: "{{ 'mongodb' in (elao_apt_repositories|select('mapping')|rejectattr('pattern', 'undefined')|map(attribute='pattern')|list + (_elao_apt_preferences_repositories|default([]) + elao_apt_repositories|select('string')|list)|unique) }}"

- name: repositories > Keys
  apt_key:
    url:   "{{ (item.key.url) if (item.key is defined) else elao_apt_repositories_patterns[item.pattern].key.url }}"
    id:    "{{ (item.key.id) if (item.key is defined) else elao_apt_repositories_patterns[item.pattern].key.id }}"
    state: "{{ item.state|default('present') }}"
  with_items: "{{ elao_apt_repositories|select('mapping')|list }}"
  when: (item.key is defined) or (elao_apt_repositories_patterns[item.pattern].key is defined)

- name: repositories > Sources
  apt_repository:
    repo:         "{{ item.source|default(elao_apt_repositories_patterns[item.pattern].source) }}"
    state:        "{{ item.state|default('present') }}"
    update_cache: yes
  with_items: "{{ elao_apt_repositories|select('mapping')|list }}"

- name: repositories > String patterns keys
  apt_key:
    url:   "{{ elao_apt_repositories_patterns[item].key.url }}"
    id:    "{{ elao_apt_repositories_patterns[item].key.id }}"
    state: present
  with_items: "{{ (_elao_apt_preferences_repositories|default([]) + elao_apt_repositories|select('string')|list)|unique }}"
  when: elao_apt_repositories_patterns[item].key is defined

- name: repositories > String pattern sources
  apt_repository:
    repo:         "{{ elao_apt_repositories_patterns[item].source }}"
    state:        present
    update_cache: yes
  with_items: "{{ (_elao_apt_preferences_repositories|default([]) + elao_apt_repositories|select('string')|list)|unique }}"
