---
- name: requirements > Node check
  command: "node --version"
  always_run: yes
  failed_when: false
  changed_when: false
  register: _elao_node_check_output

- name: requirements > Node check fail
  fail:
    msg: Need node, you can use https://github.com/ElaoInfra/ansible-role-nodejs
  when: _elao_node_check_output.stdout is not defined
