---

- name: requirements > Composer check
  command: "composer --version"
  always_run: yes
  failed_when: false
  changed_when: false
  register: _elao_composer_check_output

- name: requirements > Composer
  fail:
    msg: Need composer, you can use https://github.com/ElaoInfra/ansible-role-composer
  when: (_elao_composer_check_output.stdout is not defined)
