---

- name: resolv > Template
  template:
    src:  "{{ elao_network_resolv_template|ternary(elao_network_resolv_template, 'resolv/empty.conf.j2') }}"
    dest: "{{ elao_network_resolv_file }}"
  when: (elao_network_resolv_template is not none) or (elao_network_resolv_config|length)
