---

- name: roles > Requirements template
  template:
    src:  roles/requirements.j2
    dest: /tmp/manala_ansible_galaxy_roles.yml
  when: manala_ansible_galaxy_roles|length

- name: roles > Install
  command: >
    ansible-galaxy install
    --role-file=/tmp/manala_ansible_galaxy_roles.yml
    {{ manala_ansible_galaxy_roles_path|ternary('--roles-path=' ~ manala_ansible_galaxy_roles_path, '') }}
    {{ manala_ansible_galaxy_force|ternary('--force', '') }}
  when: manala_ansible_galaxy_roles|length
