---

- name: sudoers > Templates
  template:
    src:  "{{ item.template|default('sudoers/empty.j2') }}"
    dest: "{{ elao_sudo_sudoers_dir }}/{{ item.file }}"
    mode: 0440
  with_items: "{{ elao_sudo_sudoers }}"

- name: sudoers > Exclusive - find files
  command: "find -type f \\( ! -iname 'README' \\) -printf '%P\n'"
  args:
    chdir: "{{ elao_sudo_sudoers_dir }}"
  changed_when: false
  register: __elao_sudo_sudoers_find
  when: elao_sudo_sudoers_exclusive

- name: sudoers > Exclusive - remove files
  file:
    path:  "{{ elao_sudo_sudoers_dir }}/{{ item }}"
    state: absent
  when: elao_sudo_sudoers_exclusive and (item not in elao_sudo_sudoers|map(attribute='file'))
  with_items: "{{ __elao_sudo_sudoers_find|skipped|ternary([], __elao_sudo_sudoers_find.stdout_lines) }}"
  notify:
    - sudo restart
