---

- name: sudo > Sudoers
  template:
    src:  install/sudoers.j2
    dest: /etc/sudoers.d/pam_ssh_agent_auth
  notify:
    - sudo restart

- name: sudo > Pam
  lineinfile:
    dest:         /etc/pam.d/sudo
    line:         'auth sufficient pam_ssh_agent_auth.so file=%h/.ssh/authorized_keys'
    insertbefore: '^@include common-auth'
    state:        present
  notify:
    - sudo restart
