---

- name: theme > Directory
  file:
    path:  "{{ manala_ohmyzsh_dir }}/custom/themes"
    state: directory

- name: themes > Templates
  template:
    src:   "themes/{{ item }}.j2"
    dest:  "{{ manala_ohmyzsh_dir }}/custom/themes/{{ item }}"
  with_items:
    - manala-dev.zsh-theme
    - manala-demo.zsh-theme
    - manala-prod.zsh-theme
