---

- name: users > Configuring users accounts
  user:
    name:       "{{ item.name }}"
    group:      "{{ item.group }}"
    groups:     "{{ item.groups|default([])|join(',') }}"
    createhome: "{{ item.createHome|default(omit) }}"
    system:     "{{ item.system|default(omit) }}"
  with_items: elao_users
