---

- name: vars > Packages
  set_fact:
    __item: "{{
      ((__manala_npm_packages_results|default({'ansible_facts':{'__item':{}}})).ansible_facts.__item)|combine(
        (
          {
            item: {
              'package': item
            }
          }
        ) if (item is string) else (
          {
            item.package: item
          }
        )
      )
    }}"
  with_items: "{{ manala_npm_packages }}"
  register: __manala_npm_packages_results
