---

- name: writable > Dirs stat
  stat:
    path:  "{{ deploy_helper.new_release_path ~ '/' ~ item }}"
  register: __manala_deploy_writable_dirs_stats_output
  with_items: "{{ manala_deploy_writable_dirs }}"

- name: writable > Dirs
  file:
    path:    "{{
      (__manala_deploy_writable_dirs_stats_output.results[item.0].stat.islnk|default(false))|ternary(
        __manala_deploy_writable_dirs_stats_output.results[item.0].stat.lnk_source,
        deploy_helper.new_release_path ~ '/' ~ item.1
      )
    }}"
    recurse: true
    mode:    "{{ manala_deploy_writable_dirs_mode }}"
    state:   directory
  with_indexed_items: "{{ manala_deploy_writable_dirs }}"
