---

- name: attributes > Link directory - Directory "{{ item.src }}"
  file:
    path:    "{{ item.src }}"
    follow:  "{{ item.follow|default(omit) }}"
    recurse: "{{ item.recurse|default(true) }}"
    force:   "{{ item.force|default(omit) }}"
    owner:   "{{
      item.user|default(
        manala_files_attributes_user|ternary(manala_files_attributes_user, omit)
      )
    }}"
    group:   "{{
      item.group|default(
        manala_files_attributes_group|ternary(manala_files_attributes_group, omit)
      )
    }}"
    mode:    "{{ item.mode|default(omit) }}"
    state:   directory

- name: attributes > Link directory - Stat link "{{ item.path }}"
  stat:
    path: "{{ item.path }}"
  register: __manala_files_stat

- name: attributes > Link directory - Move directory content "{{ item.path }}"
  shell: mv {{ item.path }}/* {{ item.src }}
  when: __manala_files_stat.stat.isdir|default(false)

- name: attributes > Link directory - Link "{{ item.path }}"
  file:
    path:    "{{ item.path }}"
    follow:  "{{ item.follow|default(omit) }}"
    recurse: "{{ item.recurse|default((item.state == 'directory')|ternary(true, omit)) }}"
    src:     "{{ item.src|default(omit) }}"
    force:   true
    owner:   "{{ omit }}"
    group:   "{{ omit }}"
    mode:    "{{ item.mode|default(omit) }}"
    state:   link
