---

- name: files > Url "{{ item.path }}"
  get_url:
    dest:           "{{ item.path }}"
    url:            "{{ item.url }}"
    validate_certs: "{{ item.validate_certs|default(true)|bool }}"
    force:          "{{ item.force|default(omit) }}"
    owner:          "{{
      item.user|default(
        manala_files_attributes_user|ternary(manala_files_attributes_user, omit)
      )
    }}"
    group:          "{{
      item.group|default(
        manala_files_attributes_group|ternary(manala_files_attributes_group, omit)
      )
    }}"
    mode:           "{{ item.mode|default(omit) }}"
