---

- name: sensu restart
  service:
    name:  "{{ item }}"
    state: restarted
  with_items: elao_sensu_services

- name: sensu-server restart
  service:
    name:  sensu-server
    state: restarted

- name: sensu-api restart
  service:
    name:  sensu-api
    state: restarted

- name: sensu-client restart
  service:
    name:  sensu-client
    state: restarted
